### ISSUE TITLE
Install on Debian

### ISSUE THREAD

**Issue by masooddalman** [VZiChoushaDui/Libertea#4] opened 2023-01-26 07:50 UTC
is there any chance to install it on Debian?

**Comment by VZiChoushaDui** [comment] 2023-01-28 09:08
We haven't tested it on Debian, but it might just work, as Ubuntu is a Debian-based distro.

Try it, and let us know if there are any issues so we can fix it.

**Comment by masooddalman** [comment] 2023-01-28 10:54
@VZiChoushaDui 

Actually I've tried once and it wasn't successful. It couldn't find ubuntu firewall. Error: `cannot find ufw`

**Comment by VZiChoushaDui** [comment] 2023-01-28 11:26
@masooddalman Can you try installing ufw first and see if the rest works?

    sudo apt install -y ufw

**Comment by masooddalman** [comment] 2023-01-28 12:12
@VZiChoushaDui 
Thanks, it successfully installed after installing ufw.
but my domain in behind Cloudflare, I wrote it during installation. now when I try to open admin panel, nothing happens!

any suggestion?

![image](https://user-images.githubusercontent.com/22127399/215265821-f89f657d-d343-4aa4-8249-afb7787e0761.png)

**Comment by VZiChoushaDui** [comment] 2023-01-28 13:32
@masooddalman What about the IP-based admin url?

**Comment by masooddalman** [comment] 2023-01-28 14:19
@VZiChoushaDui 
same.

Do I need to add any port at the end of the domain/IP to access admin panel?

**Comment by VZiChoushaDui** [comment] 2023-01-29 08:57
@masooddalman No. Probably panel service is failing to run.

Please run the following command and post the results here:

    tail --lines=500 /tmp/libertea-panel.log

Please check the logs before posting, if your server ip is visible in the logs, delete it for your security.

**Comment by masooddalman** [comment] 2023-01-29 10:13
@VZiChoushaDui 
interesting!
have a look please 🙏

```
root@109:~# tail --lines=500 /tmp/libertea-panel.log
tail: cannot open '/tmp/libertea-panel.log' for reading: No such file or directory
```

**Comment by VZiChoushaDui** [comment] 2023-01-30 08:41
@masooddalman 

We've fixed compatibility issues with Debian 11.

Please run the following commands on a root shell to uninstall Libertea, and then install it again from scratch:

    cd /root/libertea
    docker compose down
    cd /root
    rm -rf /root/libertea

**Comment by masooddalman** [comment] 2023-01-30 09:25
@VZiChoushaDui 

I receive new error, I don't know if it is related to `Libertea` or my `VPS`.

![image](https://user-images.githubusercontent.com/22127399/215437708-4c193bb0-0e98-4c0a-abc8-03581e86097c.png)

```
[+] Building 13.7s (4/7)
 => [internal] load build definition from Dockerfile                                                   0.1s
[+] Building 13.8s (4/7)
 => [internal] load build definition from Dockerfile                                                   0.1s
[+] Building 13.9s (4/7)
 => [internal] load build definition from Dockerfile                                                   0.1s
 => => transferring dockerfile: 31B                                                                    0.1s
 => [internal] load .dockerignore                                                                      0.1s
 => => transferring context: 2B                                                                        0.1s
 => [internal] load metadata for docker.io/library/python:3.10                                         1.2s
[+] Building 14.0s (4/7)
[+] Building 13.9s (6/8)
 => [internal] load build definition from Dockerfile                                                   0.1s
 => => transferring dockerfile: 32B                                                                    0.1s
 => [internal] load .dockerignore                                                                      0.1s
 => => transferring context: 2B                                                                        0.1s
 => [internal] load metadata for docker.io/teddysun/xray:latest                                        1.2s
 => CACHED [1/4] FROM docker.io/teddysun/xray:latest@sha256:58726d1c48b7d426a9113d1e0a0a9b426c08662eb  0.0s
 => ERROR [2/4] RUN apk update && apk add iptables                                                    11.9s
 => [internal] load build context                                                                      0.1s
 => => transferring context: 35B                                                                       0.1s
------
 > [2/4] RUN apk update && apk add iptables:
[+] Building 14.1s (5/6)
 => [internal] load build definition from Dockerfile                                                   0.1s
 => => transferring dockerfile: 32B                                                                    0.1s
 => [internal] load .dockerignore                                                                      0.1s
 => => transferring context: 2B                                                                        0.1s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                        1.1s
 => CACHED [1/3] FROM docker.io/library/ubuntu:22.04@sha256:27cb6e6ccef575a4698b66f5de06c7ecd61589132  0.0s
 => CANCELED [2/3] RUN apt-get update && apt-get install rsyslog -y                                   12.0s
failed to solve: executor failed running [/bin/sh -c apk update && apk add iptables]: exit code: 2

```

**Comment by VZiChoushaDui** [comment] 2023-02-02 08:36
I currently have no idea what the problem is, as it's working fine on our test Debian machines.

**Comment by masooddalman** [comment] 2023-02-02 16:43
I just installed it on an ubuntu machine, and it works. however the protocol is already ban in my country.

but thanks for your work. it is a great tool. 🙏

**Comment by VZiChoushaDui** [comment] 2023-02-10 12:00
The issue mentioned in the latest screenshot is now fixed.

**Closed by VZiChoushaDui** 2023-02-10 12:00 UTC
